const COMPENSATION_CATEGORIES = {
  EX_GRATIA: "EX_GRATIA",
  AGRICULTURAL: "AGRICULTURAL",
  HOUSING: "HOUSING",
  LIVESTOCK: "LIVESTOCK",
  OTHER: "OTHER",
};

const COMPENSATION_CATEGORY_VALUES = Object.values(COMPENSATION_CATEGORIES);

module.exports = {
  COMPENSATION_CATEGORIES,
  COMPENSATION_CATEGORY_VALUES,
};
